version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env

  mariadb:
    image: mariadb:10.8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vyxsuit_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb-init.sql:/docker-entrypoint-initdb.d/mariadb-init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mariadb_data:
